
: SKIP-NON-DIGIT ( -- n )
    BEGIN KEY DIGIT? 0= WHILE REPEAT ;

: GET-NUMBER ( -- n )
    0 SKIP-NON-DIGIT
    BEGIN
        SWAP 10 * +
        KEY DIGIT?
    0= UNTIL ;

256 CONSTANT MAX-ROUTES
CREATE ROUTES MAX-ROUTES CELLS ALLOT
VARIABLE ROUTE-MAX
0 ROUTE-MAX !

: NEW-ROUTE
    ROUTES ROUTE-MAX @ CELLS + HERE SWAP !
    1 ROUTE-MAX +! ;

: GET-ROUTE
    NEW-ROUTE
    GET-NUMBER DUP ,
    0 DO GET-NUMBER C, LOOP ;

: GET-ROUTES
    0 ROUTE-MAX !
    GET-NUMBER 0 DO GET-ROUTE LOOP ;

GET-ROUTES
ROUTES 0 CELLS + @ 20 DUMP cr
ROUTES 1 CELLS + @ 20 DUMP cr
ROUTES 2 CELLS + @ 20 DUMP cr
BYE



